// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Field: typeof import('./../components/form/Field.vue')['default']
    Footer: typeof import('./../components/layout/Footer.vue')['default']
    Header: typeof import('./../components/layout/Header.vue')['default']
    Icons: typeof import('./../components/others/Icons.vue')['default']
    Modal: typeof import('./../components/modals/Modal.vue')['default']
  }
}

export { }
